### ISSUE TITLE
Make debug output consistently grep-able by project name

### ISSUE THREAD

**Issue by mcomella** [zach-r-d/contribgames#2]
The debug output would more useful to game maintainers implementing a .games.json file if the output could be piped to grep with a project name and thus only relevant output for that project would show.

For example, `games -vv list | grep rapt` would only show any errors pertaining to rapt. The ability to do this should be documented in the readme.

The debug output format could be similar to:

```
DEBUG:root:rapt:No valid .json file found.
```

where `DEBUG:root` is the default logging module output and the next field is the project name.

**Comment by zach-r-d** [comment]
Fully support this.

**Comment by zach-r-d** [comment]
Added in the loggingimprovements branch.
