### ISSUE TITLE
"manual" directory name is confusing

### ISSUE THREAD

**Issue by mcomella** [zach-r-d/contribgames#5]
I initially thought this directory contained "man" pages, as opposed to manual entries into the games list.

Perhaps it should be called "manual_entries" or something similar. It might be a good idea to make it a hidden directory as well.

The code would have to be changed accordingly (in addition to the removal of the `TODO` in the code).

**Comment by zach-r-d** [comment]
It's definitely worth changing the name, ideally to something that makes it clear that entries in that folder override .games.json files in respective project folders (I don't think this is documented anywhere).

What benefit would there be in making the directory hidden?

**Comment by mcomella** [comment]
It makes the root directory of the contrib project a little cleaner for someone who's trying to poke around (since the overrides are only really relevant to the project maintainer) but I suppose it really doesn't matter.

On the other hand, making it visible might be worthwhile so the next maintainer is more likely to be aware of its existence.

**Comment by zach-r-d** [comment]
Yeah, I think it's better to leave it visible so everyone who pokes around or maintains the project knows about it rather than trying to hide it so it looks like magic.

If you don't get around to this earlier I'll do it on during my shift on Monday.

**Comment by zach-r-d** [comment]
Changed to overrides/ in 76ca78432466f96569a11906a59cbf42f7d4a4a5.
