### ISSUE TITLE
Remove .acl from repo

### ISSUE THREAD

**Issue by mcomella** [zach-r-d/contribgames#6]
I don't think it belongs here. What do you think?

**Comment by zach-r-d** [comment]
Removing it from the repo and adding it to gitignore is fine, but we should leave the file on the filesystem because it'd be annoying to rewrite.

**Comment by mcomella** [comment]
Agreed. I don't have read access to /contrib/projects/games/.acl so you'll have to give me permissions to it or take care of the change yourself.

**Comment by zach-r-d** [comment]
I did both. Fixed in ff609ca.

**Comment by mcomella** [comment]
Great, thanks.

Unrelated: If you use the full commit hash, github will auto-link it for you.
